src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChambreRepository::class)
 */
class Chambre
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Num;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $etage;

    /**
     * @ORM\OneToMany(targetEntity=Location::class, mappedBy="Chambre")
     */
    private $locations;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Tarif;

    public function __construct()
    {
        $this->locations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNum(): ?int
    {
        return $this->Num;
    }

    public function setNum(int $Num): self
    {
        $this->Num = $Num;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getEtage(): ?int
    {
        return $this->etage;
    }

    public function setEtage(?int $etage): self
    {
        $this->etage = $etage;

        return $this;
    }

    /**
     * @return Collection|Location[]
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): self
    {
        if (!$this->locations->contains($location)) {
            $this->locations[] = $location;
            $location->setChambre($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): self
    {
        if ($this->locations->contains($location)) {
            $this->locations->removeElement($location);
            // set the owning side to null (unless already changed)
            if ($location->getChambre() === $this) {
                $location->setChambre(null);
            }
        }

        return $this;
    }

    public function getTarif(): ?int
    {
        return $this->Tarif;
    }

    public function setTarif(?int $Tarif): self
    {
        $this->Tarif = $Tarif;

        return $this;
    }
}

src/Entity/Location.php
<?php

namespace App\Entity;

use App\Repository\LocationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LocationRepository::class)
 */
class Location
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomLocataire;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PrenomLocataire;

    /**
     * @ORM\ManyToOne(targetEntity=Chambre::class, inversedBy="locations")
     * @ORM\OrderBy({"Num" = "ASC"})
     */
    private $Chambre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDeb;

    /**
     * @ORM\Column(type="date")
     */
    private $DateFin;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomLocataire(): ?string
    {
        return $this->nomLocataire;
    }

    public function setNomLocataire(string $nomLocataire): self
    {
        $this->nomLocataire = $nomLocataire;

        return $this;
    }

    public function getPrenomLocataire(): ?string
    {
        return $this->PrenomLocataire;
    }

    public function setPrenomLocataire(string $PrenomLocataire): self
    {
        $this->PrenomLocataire = $PrenomLocataire;

        return $this;
    }

    public function getChambre(): ?Chambre
    {
        return $this->Chambre;
    }

    public function setChambre(?Chambre $Chambre): self
    {
        $this->Chambre = $Chambre;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDateDeb(): ?\DateTimeInterface
    {
        return $this->DateDeb;
    }

    public function setDateDeb(\DateTimeInterface $DateDeb): self
    {
        $this->DateDeb = $DateDeb;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }
}

src/Controller/LocationController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Chambre;
use App\Entity\Location ; 
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class LocationController extends Controller
{
    /**
     * @Route("/viewLocations", name="viewLocations")
     */

    public function viewLocations() // c est une action
    {
        $em = $this->getDoctrine()->getManager();

        //Acceder a le repo et fetcher tous les locations
        $repo = $em->getRepository(Location::class);

        $locations = $repo->findBy([], ['Chambre' => 'ASC']);

        return $this->render('location/viewLocations.html.twig', [
            'locations' => $locations,
        ]);

    }

    /**
     * @Route("/louerChambre/{id}", name="louerChambre")
     */
    public function addLocation($id, Request $request){
    	$em = $this->getDoctrine()->getManager();

	        //Acceder a le repo et fetcher tous les locations
	    $repo = $em->getRepository(Location::class);
	    $repo2 = $em->getRepository(Chambre::class);

	    $chambre = $repo2->findOneById($id) ; 

    	if($request->isMethod('POST')){
	    	
	    	$data = $request->request->all();

	    	$datedeb = \DateTime::createFromFormat('Y-m-d', $data['datedeb']) ; 
	    	$datefin = \DateTime::createFromFormat('Y-m-d', $data['datefin']) ;
	    	$today = date('Y-m-d');
	    	$bool = true ;

	    	if ($datedeb > $datefin){
	    		return $this->render('location/addLocation.html.twig', [
            		'chambre' => $chambre, 'bool' => $bool, 
        		]);
	    	}

	    	/*
	    	if ($today<$datedeb){
	    		return $this->redirectToRoute('viewChambres', array('id' => $id)) ; 

	    	}*/

	        $locations = $chambre->getLocations() ; 

	        foreach($locations as $loc ){
	        	$datedeb2 = $loc->getDateDeb() ; 
	        	$datefin2 = $loc->getDateFin() ; 

	        	if ($datedeb <= $datedeb2 && $datefin > $datedeb2){
	        		$bool = false ;
	        	}


	        	if ($datedeb <= $datedeb2 && $datefin > $datefin2 ){
	        		$bool = false ; 
	        	}

	        	if ($datedeb >= $datedeb2 && $datefin < $datefin2){
	        		$bool = false ; 
	        	}

	        	if ($datedeb < $datefin2 && $datefin > $datefin2){
	        		$bool = false ; 
	        	}

	        }

	        if ($bool){
		        $location = new Location ; 

		        $location->setDatedeb(\DateTime::createFromFormat('Y-m-d', $data['datedeb'])) ; 
		        $location->setDatefin(\DateTime::createFromFormat('Y-m-d', $data['datefin'])) ;
		        $location->setNomLocataire($data['nom']) ;
		        $location->setPrenomLocataire($data['prenom']) ;
		        $location->setTelephone($data['telephone']) ;
		        $location->setChambre($chambre) ; 

		        $em->persist($location);
			    $em->flush();
			    return $this->redirectToRoute('viewLocations') ; 
			}
			else{
				return $this->render('location/addLocation.html.twig', [
            		'chambre' => $chambre, 'bool' => $bool, 
        ]);
			}
		}
		else{
			return $this->render('location/addLocation.html.twig', [
            'chambre' => $chambre,
        ]);
		}

	}

	/**
    * @Route("/deleteLocation/{id}", name="deleteLocation")
    */
	public function deleteChambreLocation($id){
        $em = $this->getDoctrine()->getManager();

        //Acceder a le repo et fetcher tous les locations
        $repo = $em->getRepository(Location::class);
        $location = $repo->findOneById($id) ;
        $locations = $repo->findAll() ;  

        $em->remove($location);
		$em->flush();

		return $this->redirectToRoute('viewLocations') ; 
		
	}


	/**
     * @Route("/modifierLocation/{id}", name="modifierLocation")
     */
    public function ModifierLocation($id, Request $request){
    	$em = $this->getDoctrine()->getManager();

	        //Acceder a le repo et fetcher tous les locations
	    $repo = $em->getRepository(Location::class);
	    $repo2 = $em->getRepository(Chambre::class);
	    $location = $repo->findOneById($id) ; 

	    $chambre = $repo2->findOneById($location->getChambre()->getId()) ; 

    	if($request->isMethod('POST')){
	    	
	    	$data = $request->request->all();

	    	$datedeb = \DateTime::createFromFormat('Y-m-d', $data['datedeb']) ; 
	    	$datefin = \DateTime::createFromFormat('Y-m-d', $data['datefin']) ;

	    	if ($datedeb > $datefin){
	    		return $this->render('location/modifierLocation.html.twig', [
            		'chambre' => $chambre, 'location'=>$location, 'erreur'=> 'Date fin doit etre supérieure à date début',
        ]);
	    	}

	    	$today = date('Y-m-d');
	    	$bool = true ;

	    	/*
	    	if ($today<$datedeb){
	    		return $this->redirectToRoute('viewChambres', array('id' => $id)) ; 

	    	}*/

	        $locations = $chambre->getLocations() ; 

	        foreach($locations as $loc ){

	        	if (!($loc == $location)){
		        	$datedeb2 = $loc->getDateDeb() ; 
		        	$datefin2 = $loc->getDateFin() ; 

		        	if ($datedeb <= $datedeb2 && $datefin > $datedeb2){
		        		$bool = false ;
		        	}


		        	if ($datedeb <= $datedeb2 && $datefin > $datefin2 ){
		        		$bool = false ; 
		        	}

		        	if ($datedeb >= $datedeb2 && $datefin < $datefin2){
		        		$bool = false ; 
		        	}

		        	if ($datedeb < $datefin2 && $datefin > $datefin2){
		        		$bool = false ; 
		        	}
	        }

	        }

	        if ($bool){
		         

		        $location->setDatedeb(\DateTime::createFromFormat('Y-m-d', $data['datedeb'])) ; 
		        $location->setDatefin(\DateTime::createFromFormat('Y-m-d', $data['datefin'])) ;
		        $location->setNomLocataire($data['nom']) ;
		        $location->setPrenomLocataire($data['prenom']) ;
		        $location->setTelephone($data['telephone']) ;
		        $location->setChambre($chambre) ; 

			    $em->flush();
			    return $this->redirectToRoute('viewLocations') ; 
			}
			else{
				return $this->render('location/modifierLocation.html.twig', [
            		'chambre' => $chambre, 'bool' => $bool, 'location'=>$location,
        ]);
			}
		}
		else{
			return $this->render('location/modifierLocation.html.twig', [
            'chambre' => $chambre, 'location'=>$location,
        ]);
		}

	}
	

}

templates/location/addLocation.html.twig
<!DOCTYPE html>
<html>
<style>
input[type=text], select {
  width: 50%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  
}
input[type=date], select {
  width: 50%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 50%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a, .dropbtn {
  display: inline-block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}

li.dropdown {
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {background-color: #f1f1f1;}

.dropdown:hover .dropdown-content {
  display: block;
  }
  #customers {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
}
</style>
<head>
<title>Ajouter une chambre</title>
</head>

<body>

<ul>
  
  
  <li class="dropdown">
    <a href="javascript:void(0)" class="dropbtn">Chambres</a>
    <div class="dropdown-content">
      <a href="/addchambre">Ajouter une chambres</a>
      <a href="/viewChambres">Gestion des chambres</a>
    </div>
  </li>

  <li><a href="/viewLocations">Locations</a></li>
</ul>

<h1>Ajouter une location pour la chambre n°{{chambre.num}} </h1>

<form method="POST" action= "/louerChambre/{{chambre.id}}">
  <label for="">Nom locataire</label><br>
  <input type="text" id="nom" name="nom"><br><br>

  <label for="">Prénom locataire</label><br>
  <input type="text" id="prenom" name="prenom"><br><br>

  <label for="">Telephone</label><br>
  <input type="number" id="tel" name="telephone"><br><br>

  <label for="">Date début</label><br>
  <input type="date" id="datedeb" name="datedeb"><br><br>

  <label for="">Date fin</label><br>
  <input type="date" id="datefin" name="datefin"><br><br>


  <input type="submit" value="Ajouter">
</form>
{% if erreur is defined %}
  {{erreur}}
{% endif %}
{% if bool is defined %}
{% if bool == false %}
    <p>La période de location séléctionné existe déjà pour cette chambre, veuiller sélectionner une autre période</p>
{% endif %}
{% endif %}


</body>
</html>

templates/location/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello LocationController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/finalExam/src/Controller/LocationController.php'|file_link(0) }}">src/Controller/LocationController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/finalExam/templates/location/index.html.twig'|file_link(0) }}">templates/location/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/location/modifierLocation.html.twig
<!DOCTYPE html>
<html>
<style>
input[type=text], select {
  width: 50%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  
}
input[type=date], select {
  width: 50%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 50%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a, .dropbtn {
  display: inline-block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}

li.dropdown {
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {background-color: #f1f1f1;}

.dropdown:hover .dropdown-content {
  display: block;
  }
  #customers {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
}
</style>
<head>
<title>Ajouter une chambre</title>
</head>

<body>

<ul>
  
  
  <li class="dropdown">
    <a href="javascript:void(0)" class="dropbtn">Chambres</a>
    <div class="dropdown-content">
      <a href="/addchambre">Ajouter une chambres</a>
      <a href="/viewChambres">Gestion des chambres</a>
    </div>
  </li>

  <li><a href="/viewLocations">Locations</a></li>
</ul>

<h1>Modifier la location pour la chambre n°{{chambre.num}} </h1>

<form method="POST" action= "/modifierLocation/{{location.id}}">
  <label for="">Nom locataire</label><br>
  <input type="text" id="nom" name="nom"><br><br>

  <label for="">Prénom locataire</label><br>
  <input type="text" id="prenom" name="prenom"><br><br>

  <label for="">Telephone</label><br>
  <input type="number" id="tel" name="telephone"><br><br>

  <label for="">Date début</label><br>
  <input type="date" id="datedeb" name="datedeb"><br><br>

  <label for="">Date fin</label><br>
  <input type="date" id="datefin" name="datefin"><br><br>


  <input type="submit" value="Ajouter">
</form>

{% if bool is defined %}
{% if bool == false %}
    <p>La période de location séléctionné existe déjà pour cette chambre, veuiller sélectionner une autre période</p>
{% endif %}
{% endif %}


</body>
</html>

templates/location/viewLocations.html.twig
<!DOCTYPE html>
<html>
<head>
<style>
input[type=text], select {
  width: 50%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  
}
input[type=date], select {
  width: 50%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 50%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a, .dropbtn {
  display: inline-block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}

li.dropdown {
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {background-color: #f1f1f1;}

.dropdown:hover .dropdown-content {
  display: block;
  }
  #customers {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
}
</style>


</head>
<body>

  <ul>
  
  
  <li class="dropdown">
    <a href="javascript:void(0)" class="dropbtn">Chambres</a>
    <div class="dropdown-content">
      <a href="addchambre">Ajouter une chambres</a>
      <a href="viewChambres">Gestion des chambres</a>
    </div>
  </li>

  <li><a href="viewLocations">Locations</a></li>
</ul>

<br/>


<table id="customers">
  <tr>
    <th>Numero de Chambre</th>
    <th>Date Debut</th>
    <th>Date Fin</th>
    <th>Nom et prénom Locataire</th>
    <th>Tel locataire</th>
    <th>Tarif total</th>
    <th>Modifier</th>
    <th>Supprimer</th>
  </tr>
  {% for location in locations %}
  {% set difference = date(location.DateFin|date('Y/m/d')).diff(date(location.DateDeb|date('Y/m/d'))) %}
  {% set leftDays = difference.days + 1 %}
  {% set Tariftot = leftDays * location.chambre.Tarif %}
    
  <tr>
    <td>{{ location.chambre.Num }}</td>
    <td>{{ location.DateDeb|date("m/d/Y") }}</td>
    <td>{{ location.DateFin|date("m/d/Y") }}</td>
    <td>{{ location.NomLocataire }} {{ location.PrenomLocataire }}</td>
    <td>{{ location.Telephone }}</td>
    <td>{{ Tariftot }}</td>

    <td><a href = "modifierLocation/{{ location.id }}" type = "button">Modifier</a></td>
    <td><a href = "deleteLocation/{{ location.id }}" type = "button">Supprimer</a></td>
  </tr>
  
  {% endfor %}
</table>

</body>
</html>

</html>